"""added mammaprint column to patient_entries table

Revision ID: 6f5dadd098b3
Revises: 45ebc20307c9
Create Date: 2025-11-17 13:16:11.289963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5dadd098b3'
down_revision: Union[str, Sequence[str], None] = '45ebc20307c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctors', ['id'])
    op.add_column('patient_entries', sa.Column('mp', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'patient_entries', ['id'])
    op.create_unique_constraint(None, 'patient_prognoses', ['id'])
    op.create_unique_constraint(None, 'patients', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'patient_prognoses', type_='unique')
    op.drop_constraint(None, 'patient_entries', type_='unique')
    op.drop_column('patient_entries', 'mp')
    op.drop_constraint(None, 'doctors', type_='unique')
    # ### end Alembic commands ###
